/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl typo admin and auth api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LobbyPlayerDto
 */
export interface LobbyPlayerDto {
    /**
     * Player name
     * @type {string}
     * @memberof LobbyPlayerDto
     */
    name: string;
    /**
     * Player score
     * @type {number}
     * @memberof LobbyPlayerDto
     */
    score: number;
    /**
     * Whether the player is the drawer
     * @type {boolean}
     * @memberof LobbyPlayerDto
     */
    drawing: boolean;
    /**
     * Player join ID
     * @type {number}
     * @memberof LobbyPlayerDto
     */
    lobbyPlayerID: number;
}

/**
 * Check if a given object implements the LobbyPlayerDto interface.
 */
export function instanceOfLobbyPlayerDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "score" in value;
    isInstance = isInstance && "drawing" in value;
    isInstance = isInstance && "lobbyPlayerID" in value;

    return isInstance;
}

export function LobbyPlayerDtoFromJSON(json: any): LobbyPlayerDto {
    return LobbyPlayerDtoFromJSONTyped(json, false);
}

export function LobbyPlayerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LobbyPlayerDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['Name'],
        'score': json['Score'],
        'drawing': json['Drawing'],
        'lobbyPlayerID': json['LobbyPlayerID'],
    };
}

export function LobbyPlayerDtoToJSON(value?: LobbyPlayerDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'Score': value.score,
        'Drawing': value.drawing,
        'LobbyPlayerID': value.lobbyPlayerID,
    };
}

