/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl typo admin and auth api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PalantirLobbyPlayerDto
 */
export interface PalantirLobbyPlayerDto {
    /**
     * Player ingame name
     * @type {string}
     * @memberof PalantirLobbyPlayerDto
     */
    name: string;
    /**
     * Player login
     * @type {string}
     * @memberof PalantirLobbyPlayerDto
     */
    login: string;
    /**
     * Player account username
     * @type {string}
     * @memberof PalantirLobbyPlayerDto
     */
    username: string;
}

/**
 * Check if a given object implements the PalantirLobbyPlayerDto interface.
 */
export function instanceOfPalantirLobbyPlayerDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "login" in value;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function PalantirLobbyPlayerDtoFromJSON(json: any): PalantirLobbyPlayerDto {
    return PalantirLobbyPlayerDtoFromJSONTyped(json, false);
}

export function PalantirLobbyPlayerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PalantirLobbyPlayerDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'login': json['login'],
        'username': json['username'],
    };
}

export function PalantirLobbyPlayerDtoToJSON(value?: PalantirLobbyPlayerDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'login': value.login,
        'username': value.username,
    };
}

