/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl typo admin and auth api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PalantirLobbyDto
 */
export interface PalantirLobbyDto {
    /**
     * Lobby description
     * @type {string}
     * @memberof PalantirLobbyDto
     */
    description: string;
    /**
     * Lobby invite encrypted
     * @type {string}
     * @memberof PalantirLobbyDto
     */
    key: string;
    /**
     * Lobby unique id
     * @type {string}
     * @memberof PalantirLobbyDto
     */
    iD: string;
    /**
     * Lobby visibility restriction
     * @type {string}
     * @memberof PalantirLobbyDto
     */
    restriction: string;
}

/**
 * Check if a given object implements the PalantirLobbyDto interface.
 */
export function instanceOfPalantirLobbyDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "iD" in value;
    isInstance = isInstance && "restriction" in value;

    return isInstance;
}

export function PalantirLobbyDtoFromJSON(json: any): PalantirLobbyDto {
    return PalantirLobbyDtoFromJSONTyped(json, false);
}

export function PalantirLobbyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PalantirLobbyDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['Description'],
        'key': json['Key'],
        'iD': json['ID'],
        'restriction': json['Restriction'],
    };
}

export function PalantirLobbyDtoToJSON(value?: PalantirLobbyDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Description': value.description,
        'Key': value.key,
        'ID': value.iD,
        'Restriction': value.restriction,
    };
}

