/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl typo admin and auth api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDiscordID
 */
export interface UpdateDiscordID {
    /**
     * The id of the new linked discord account
     * @type {string}
     * @memberof UpdateDiscordID
     */
    id: string;
}

/**
 * Check if a given object implements the UpdateDiscordID interface.
 */
export function instanceOfUpdateDiscordID(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function UpdateDiscordIDFromJSON(json: any): UpdateDiscordID {
    return UpdateDiscordIDFromJSONTyped(json, false);
}

export function UpdateDiscordIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDiscordID {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function UpdateDiscordIDToJSON(value?: UpdateDiscordID | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

