/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl typo admin and auth api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookDto
 */
export interface WebhookDto {
    /**
     * The webhook name
     * @type {string}
     * @memberof WebhookDto
     */
    name: string;
    /**
     * The webhook's guild name
     * @type {string}
     * @memberof WebhookDto
     */
    guild: string;
    /**
     * The webhook URL
     * @type {string}
     * @memberof WebhookDto
     */
    uRL: string;
}

/**
 * Check if a given object implements the WebhookDto interface.
 */
export function instanceOfWebhookDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "guild" in value;
    isInstance = isInstance && "uRL" in value;

    return isInstance;
}

export function WebhookDtoFromJSON(json: any): WebhookDto {
    return WebhookDtoFromJSONTyped(json, false);
}

export function WebhookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['Name'],
        'guild': json['Guild'],
        'uRL': json['URL'],
    };
}

export function WebhookDtoToJSON(value?: WebhookDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'Guild': value.guild,
        'URL': value.uRL,
    };
}

